language: python

services:
  - docker

script:
  - make start-local
  - docker exec dj01 python /code/src/manage.py check
  - make stop
  - make clean
  - make start-prod
  - docker exec dj01 python /code/src/manage.py check
  - make stop
  - make clean