version: '3'

services:
  db:
    image: postgres:13
    container_name: db01
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    volumes:
      - ~/variant-alert/postgres-data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    networks:
      - hutch

  web:
    build: .
    container_name: dj01
    command: >
      bash -c "cd src && python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn variant_alert.wsgi -b 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/code
    expose:
      - "8000"
    networks:
      - hutch
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/prod:/etc/nginx/conf.d
      - ./config/ssl:/etc/ssl/certs
      - ./src/static:/static
    depends_on:
      - web
    networks:
      - hutch

networks:
  hutch:
    ipam:
      config:
        - subnet: 172.27.0.0/16
