# Generated by Django 2.2.17 on 2020-12-16 18:17

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('chromosome', models.CharField(choices=[('chr1', 'chr1'), ('chr2', 'chr2'), ('chr3', 'chr3'), ('chr4', 'chr4'), ('chr5', 'chr5'), ('chr6', 'chr6'), ('chr7', 'chr7'), ('chr8', 'chr8'), ('chr9', 'chr9'), ('chr10', 'chr10'), ('chr11', 'chr11'), ('chr12', 'chr12'), ('chr13', 'chr13'), ('chr14', 'chr14'), ('chr15', 'chr15'), ('chr16', 'chr16'), ('chr17', 'chr17'), ('chr18', 'chr18'), ('chr19', 'chr19'), ('chr20', 'chr20'), ('chr21', 'chr21'), ('chr22', 'chr22'), ('chrX', 'chrX'), ('chrY', 'chrY')], default='1', max_length=5)),
                ('position', models.PositiveIntegerField(blank=True)),
                ('variant_ref', models.CharField(choices=[('A', 'A'), ('C', 'C'), ('G', 'G'), ('T', 'T')], default='A', max_length=1)),
                ('variant_alt', models.CharField(choices=[('A', 'A'), ('C', 'C'), ('G', 'G'), ('T', 'T')], default='A', max_length=1)),
                ('assembly', models.CharField(choices=[('hg19', 'hg19'), ('hg38', 'hg38')], default='hg19', max_length=5)),
                ('query', models.CharField(blank=True, max_length=25)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('previous', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('difference', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('update', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('alert', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
