# Generated by Django 2.2.28 on 2022-07-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0008_auto_20220706_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='query',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
